export default {
  'GET_RECIPES' : 'GET_RECIPES',
  'GET_RECIPES_SUCCESS': 'GET_RECIPES_SUCCESS',
  'GET_RECIPES_ERROR': 'GET_RECIPES_ERROR',

  'GET_RECIPE_BY_ID': 'GET_RECIPE_BY_ID',
  'GET_RECIPE_BY_ID_SUCCESS': 'GET_RECIPE_BY_ID_SUCCESS',
  'GET_RECIPE_BY_ID_ERROR': 'GET_RECIPE_BY_ID_ERROR',

  'GET_CHEFS' : 'GET_CHEFS',
  'GET_CHEFS_SUCCESS': 'GET_CHEFS_SUCCESS',
  'GET_CHEFS_ERROR': 'GET_CHEFS_ERROR',

  'GET_CHEF_BY_ID' : 'GET_CHEF_BY_ID',
  'GET_CHEF_BY_ID_SUCCESS': 'GET_CHEF_BY_ID_SUCCESS',
  'GET_CHEF_BY_ID_ERROR': 'GET_CHEF_BY_ID_ERROR',

  'GET_INGREDIENTS' : 'GET_INGREDIENTS',
  'GET_INGREDIENTS_SUCCESS': 'GET_INGREDIENTS_SUCCESS',
  'GET_INGREDIENTS_ERROR': 'GET_INGREDIENTS_ERROR',

  'GET_INGREDIENT_BY_ID' : 'GET_INGREDIENT_BY_ID',
  'GET_INGREDIENT_BY_ID_SUCCESS': 'GET_INGREDIENT_BY_ID_SUCCESS',
  'GET_INGREDIENT_BY_ID_ERROR': 'GET_INGREDIENT_BY_ID_ERROR',

  'GET_GALLERIES' : 'GET_GALLERIES',
  'GET_GALLERIES_SUCCESS': 'GET_GALLERIES_SUCCESS',
  'GET_GALLERIES_ERROR': 'GET_GALLERIES_ERROR',

  'GET_GALLERIE_BY_ID' : 'GET_GALLERIE_BY_ID',
  'GET_GALLERIE_BY_ID_SUCCESS': 'GET_GALLERIE_BY_ID_SUCCESS',
  'GET_GALLERIE_BY_ID_ERROR': 'GET_GALLERIE_BY_ID_ERROR',
}